### ISSUE TITLE
Duplicate key name 'tx_index' error on rps.sql

### ISSUE THREAD

**Issue by y-zono** [jdogresorg/counterparty2mysql#1]
https://github.com/jdogresorg/counterparty2mysql/blob/master/sql/rps.sql#L3

I think ```tx_index INTEGER UNSIGNED``` is correct. I got ```Duplicate key name 'tx_index'``` error when I import the sql.

```
CREATE TABLE rps (
    tx_index            INTEGER UNIQUE,

CREATE UNIQUE INDEX tx_index            ON rps (tx_index);
```

**Comment by jdogresorg** [comment]
I have run into that issue a few times as well... at the time CP was experiencing some issues and I just resolved by deleting the duplicate record....`DELETE FROM XXXX where tx_index=YYY` .... not an ideal solution... but works for now until I have time to track down exactly why the failure is happening

**Comment by y-zono** [comment]
I also had the same issue, duplicating tx_index or tx_hash_id, sometimes. (not a lot, rarely)
Seems it works after I added a deletion method for the duplicated records.
