### ISSUE TITLE
Is data consistency maintained after reorganization?

### ISSUE THREAD

**Issue by y-zono** [jdogresorg/counterparty2mysql#2]
I want to build counterparty transaction explorer like you. Your tool is awesome. Counterparty data was imported into my mysql db by using the tool. Then it is executed every minute by cron job.

I have one question about reorganization. As far as I have seen the tool and counterparyd code, I think I have to do something for reorg since your tool retrieves message records at the highest block (from LASTFILE) when the tool's block argument is empty. 

I'm not sure my thought but are you doing anything for reorg?

**Comment by jdogresorg** [comment]
Currently reorgs are handled manually by re-parsing the reorg block and all blocks since.... nothing setup in the script yet to detect/handle reorgs

**Comment by y-zono** [comment]
Thank you. I will do it too.
