### ISSUE TITLE
BootStrap data. Can you use CHARSET=utf8 instead of latin1?

### ISSUE THREAD

**Issue by y-zono** [jdogresorg/counterparty2mysql#3]
Thank you for your great job. Your tool is very useful for me.

**Summary**

I got '1267 Illegal mix of collations' error when I executed counterparty2mysql.php

**Steps to Reproduce**

1. Import the bootstrap sql. https://github.com/jdogresorg/counterparty2mysql/blob/master/bootstrap/Counterparty.sql.gz
1. Start counterparty2mysql.php

**Expected Results**

The data is imported normally.

**Actual Results**

The following error occurred.

```
$php ./counterparty2mysql.php --block=472477 --single
processing block 472477...[2018-01-18 08:51:07 UTC] - Error while trying to check if record already exists in orders : SELECT * FROM orders WHERE block_index='472477' AND expiration='5000' AND expire_index='477477' AND fee_provided='16000' AND fee_provided_remaining='16000' AND fee_required='0' AND fee_required_remaining='0' AND get_asset_id='5' AND get_quantity='0' AND get_remaining='0' AND give_asset_id='2' AND give_quantity='0' AND give_remaining='0' AND source_id='11' AND status='invalid: non‐positive give quantity; non‐positive get quantity; zero give or zero get' AND tx_hash_id='10' AND tx_index='966257'
```

I checked that $mysqli->errno was '1267 Illegal mix of collations'

**Notes**

I confirmed that orders table's charset was latin1. sqlite db in counterpartyd is using UTF-8 encoding. I think it should be the same encoding.

```
$ wget https://s3.amazonaws.com/counterparty-bootstrap/counterparty-db.latest.tar.gz
$ tar zxvf counterparty-db.latest.tar.gz 
$ sqlite counterparty.db 
sqlite> PRAGMA encoding; 
UTF-8
```

**Comment by jdogresorg** [comment]
The table definitions and bootstrap images have been updated to use UTF8 as requested :)

**Comment by y-zono** [comment]
Thank you so much. My issue was solved.
